name: Build React Native Android App

on:
  push:
    branches:
      - main  # Uruchamia proces na push do gałęzi "main"
  pull_request:
    branches:
      - main

jobs:
  test-upload:
    runs-on: ubuntu-latest

    steps:
    # 1. Utwórz pusty plik do testowania
    - name: Create a dummy APK file
      run: |
        mkdir -p $HOME/apk
        echo "Test APK content" > $HOME/apk/drugaksiazka.apk

    # 2. Instalacja kluczy SSH
    - name: Install SSH keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

    # 3. Przesyłanie pliku APK na serwer
    - name: Upload APK to server
      run: |
        scp $HOME/apk/drugaksiazka.apk ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/ubuntu/mobile_app/
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cp /home/ubuntu/mobile_app/drugaksiazka.apk /var/www/html/drugaksiazka.apk"

    # 4. Cleanup
    - name: Cleanup
      run: rm -rf ~/.ssh
