name: Build React Native Android App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Expo prebuild
        run: npx expo prebuild --platform android

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          target: android-33
          build-tools: 33.0.2

      - name: Add app icon
        run: |
          cp img/logo.png android/app/src/main/res/mipmap-hdpi/ic_launcher.png
          cp img/logo.png android/app/src/main/res/mipmap-mdpi/ic_launcher.png
          cp img/logo.png android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
          cp img/logo.png android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
          cp img/logo.png android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Rename APK
        run: mv android/app/build/outputs/apk/release/app-release.apk android/app/build/outputs/apk/release/drugaksiazka.apk

      - name: Save APK locally
        run: mkdir -p $HOME/apk && cp android/app/build/outputs/apk/release/drugaksiazka.apk $HOME/apk/drugaksiazka.apk

      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Upload APK to server
        run: |
          scp $HOME/apk/drugaksiazka.apk ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/ubuntu/mobile_app/
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cp /home/ubuntu/mobile_app/drugaksiazka.apk /var/www/html/drugaksiazka.apk"

      - name: Cleanup
        run: rm -rf ~/.ssh
